theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/logo-text.svg'
    footer: '/assets/images/logo.svg'
  posts:
    index:
      layout: grid